"""Fueling-protocol control primitives.

This module intentionally does not reproduce proprietary SAE J2601 lookup tables.
It accepts a schedule generated by an authorized table implementation, MC Formula,
or a supervisory station controller and applies it to the dynamic tank model.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import math

from .tabulated import PropsSI


def _profile_value(
    profile: tuple[tuple[float, float], ...], time_s: float, fallback: float
) -> float:
    """Linearly interpolate a frozen boundary profile without extrapolation."""
    if not profile:
        return float(fallback)
    if time_s <= profile[0][0]:
        return float(profile[0][1])
    if time_s >= profile[-1][0]:
        return float(profile[-1][1])
    for (left_time, left_value), (right_time, right_value) in zip(profile, profile[1:]):
        if time_s <= right_time:
            fraction = (time_s - left_time) / (right_time - left_time)
            return float(left_value + fraction * (right_value - left_value))
    return float(profile[-1][1])


class FuelingPhase(str, Enum):
    IDLE = "idle"
    FILLING = "filling"
    LEAK_CHECK = "leak_check"
    COMPLETE = "complete"
    ABORTED = "aborted"


@dataclass(frozen=True)
class FuelingSchedule:
    """Externally supplied SAE J2601-compatible fueling setpoints, in SI units."""

    target_pressure_pa: float
    average_pressure_ramp_rate_pa_s: float
    delivery_temperature_k: float
    maximum_mass_flow_kg_s: float
    maximum_gas_temperature_k: float = 358.15
    target_soc: float = 1.0
    nominal_working_pressure_pa: float = 70.0e6
    reference_temperature_k: float = 288.15
    delivery_temperature_profile_k: tuple[tuple[float, float], ...] = ()
    pressure_reference_profile_pa: tuple[tuple[float, float], ...] = ()
    # Optional field-procedure pause.  When set, the controller pauses at each
    # pressure increment and checks for an observable pressure decay before
    # resuming.  None preserves the historical continuous-fill behavior.
    leak_check_pressure_interval_pa: float | None = None
    leak_check_pause_s: float = 5.0
    leak_check_pressure_drop_tolerance_pa: float = 10_000.0

    def __post_init__(self) -> None:
        if self.target_pressure_pa <= 0.0:
            raise ValueError("target_pressure_pa must be positive")
        if self.average_pressure_ramp_rate_pa_s <= 0.0:
            raise ValueError("average_pressure_ramp_rate_pa_s must be positive")
        if self.maximum_mass_flow_kg_s <= 0.0:
            raise ValueError("maximum_mass_flow_kg_s must be positive")
        if self.leak_check_pressure_interval_pa is not None and self.leak_check_pressure_interval_pa <= 0.0:
            raise ValueError("leak_check_pressure_interval_pa must be positive when configured")
        if self.leak_check_pause_s <= 0.0:
            raise ValueError("leak_check_pause_s must be positive")
        if self.leak_check_pressure_drop_tolerance_pa < 0.0:
            raise ValueError("leak_check_pressure_drop_tolerance_pa must be non-negative")
        if not 0.0 < self.target_soc <= 1.2:
            raise ValueError("target_soc must be in (0, 1.2]")
        self._validate_profile(
            self.delivery_temperature_profile_k,
            "delivery_temperature_profile_k",
        )
        self._validate_profile(
            self.pressure_reference_profile_pa,
            "pressure_reference_profile_pa",
        )

    @staticmethod
    def _validate_profile(
        profile: tuple[tuple[float, float], ...], name: str
    ) -> None:
        previous_time = None
        for point in profile:
            if len(point) != 2:
                raise ValueError(f"{name} points must contain (time_s, value)")
            time_s, value = (float(item) for item in point)
            if time_s < 0.0 or not math.isfinite(time_s) or not math.isfinite(value):
                raise ValueError(f"{name} points must be finite and non-negative in time")
            if previous_time is not None and time_s <= previous_time:
                raise ValueError(f"{name} times must be strictly increasing")
            previous_time = time_s

    def delivery_temperature_at(self, time_s: float) -> float:
        return _profile_value(
            self.delivery_temperature_profile_k,
            time_s,
            self.delivery_temperature_k,
        )

    def pressure_reference_at(self, time_s: float) -> float:
        """Return a supplied J2601 pressure schedule or the PI ramp fallback."""
        if not self.pressure_reference_profile_pa:
            raise ValueError("No pressure reference profile is configured")
        return _profile_value(
            self.pressure_reference_profile_pa,
            time_s,
            self.pressure_reference_profile_pa[0][1],
        )


@dataclass(frozen=True)
class FuelingControllerParameters:
    proportional_gain_pa_inverse: float = 3.0e-8
    integral_gain_pa_inverse_s_inverse: float = 2.0e-10
    minimum_opening: float = 0.0
    maximum_opening: float = 1.0
    completion_pressure_tolerance_pa: float = 1.0e5
    anti_windup_gain: float = 0.5
    maximum_opening_slew_per_s: float = 0.03


@dataclass(frozen=True)
class FuelingObservation:
    time_s: float
    pressure_pa: float
    temperature_k: float
    density_kg_m3: float
    measured_mass_flow_kg_s: float


@dataclass(frozen=True)
class FuelingCommand:
    phase: FuelingPhase
    valve_opening: float
    reference_pressure_pa: float
    delivery_temperature_target_k: float
    state_of_charge: float
    stop_reason: str | None = None


class VehicleStateOfCharge:
    """Density-based compressed-hydrogen vehicle SOC definition."""

    def __init__(self, schedule: FuelingSchedule, fluid: str = "Hydrogen") -> None:
        self.reference_density_kg_m3 = float(
            PropsSI(
                "Dmass",
                "P",
                schedule.nominal_working_pressure_pa,
                "T",
                schedule.reference_temperature_k,
                fluid,
            )
        )

    def calculate(self, density_kg_m3: float) -> float:
        return density_kg_m3 / self.reference_density_kg_m3


class SampledFuelingController:
    """Sampled PI pressure-ramp controller with independent safety termination."""

    def __init__(
        self,
        schedule: FuelingSchedule,
        parameters: FuelingControllerParameters | None = None,
        fluid: str = "Hydrogen",
    ) -> None:
        self.schedule = schedule
        self.parameters = parameters or FuelingControllerParameters()
        self.soc_model = VehicleStateOfCharge(schedule, fluid)
        self._phase = FuelingPhase.IDLE
        self._start_time_s = 0.0
        self._initial_pressure_pa = 0.0
        self._integral_error_pa_s = 0.0
        self._last_opening = 0.0
        self._next_leak_check_pressure_pa: float | None = None
        self._leak_check_until_s: float | None = None
        self._leak_check_reference_pressure_pa: float | None = None

    def start(self, time_s: float, initial_pressure_pa: float) -> None:
        self._phase = FuelingPhase.FILLING
        self._start_time_s = time_s
        self._initial_pressure_pa = initial_pressure_pa
        self._integral_error_pa_s = 0.0
        self._last_opening = 0.0
        self._next_leak_check_pressure_pa = (
            initial_pressure_pa + self.schedule.leak_check_pressure_interval_pa
            if self.schedule.leak_check_pressure_interval_pa is not None
            else None
        )
        self._leak_check_until_s = None
        self._leak_check_reference_pressure_pa = None

    def reset(self) -> None:
        """Return the controller to idle before a separate operator fill request."""
        self._phase = FuelingPhase.IDLE
        self._integral_error_pa_s = 0.0
        self._last_opening = 0.0
        self._next_leak_check_pressure_pa = None
        self._leak_check_until_s = None
        self._leak_check_reference_pressure_pa = None

    def update(self, observation: FuelingObservation, sample_period_s: float,
               *, auto_stop: bool = True, target_pressure_pa: float | None = None) -> FuelingCommand:
        if self._phase is FuelingPhase.IDLE:
            self.start(observation.time_s, observation.pressure_pa)

        elapsed_s = max(0.0, observation.time_s - self._start_time_s)
        target = target_pressure_pa or self.schedule.target_pressure_pa
        ramp_reference = self._initial_pressure_pa + self.schedule.average_pressure_ramp_rate_pa_s * elapsed_s
        if self.schedule.pressure_reference_profile_pa:
            scheduled_reference = max(
                self._initial_pressure_pa,
                self.schedule.pressure_reference_at(elapsed_s),
            )
            reference_pressure_pa = (
                min(target, scheduled_reference)
                if auto_stop else scheduled_reference
            )
        else:
            reference_pressure_pa = min(target, ramp_reference) if auto_stop else min(110e6, ramp_reference)
        soc = self.soc_model.calculate(observation.density_kg_m3)

        if observation.temperature_k >= self.schedule.maximum_gas_temperature_k:
            self._phase = FuelingPhase.ABORTED
            return self._stopped_command(reference_pressure_pa, soc, "gas-temperature-limit")

        pressure_complete = observation.pressure_pa >= (
            target
            - self.parameters.completion_pressure_tolerance_pa
        )
        if auto_stop and (pressure_complete or soc >= self.schedule.target_soc):
            self._phase = FuelingPhase.COMPLETE
            reason = "target-pressure" if pressure_complete else "target-soc"
            return self._stopped_command(reference_pressure_pa, soc, reason)

        # Optional pressure-hold leak check.  This follows the publicly
        # documented station procedure of pausing after a pressure increment,
        # closing the inlet, and accepting the fill only when the measured
        # pressure does not decay beyond the configured tolerance.  The feature
        # is opt-in so existing continuous-fill studies remain unchanged.
        if self._phase is FuelingPhase.LEAK_CHECK:
            if self._leak_check_until_s is None or self._leak_check_reference_pressure_pa is None:
                self._phase = FuelingPhase.ABORTED
                return self._stopped_command(reference_pressure_pa, soc, "leak-test-state-error")
            if observation.time_s < self._leak_check_until_s:
                return self._paused_command(
                    reference_pressure_pa,
                    soc,
                    "leak-check-pause",
                    observation.time_s,
                )
            pressure_drop_pa = (
                self._leak_check_reference_pressure_pa - observation.pressure_pa
            )
            if pressure_drop_pa > self.schedule.leak_check_pressure_drop_tolerance_pa:
                self._phase = FuelingPhase.ABORTED
                return self._stopped_command(
                    reference_pressure_pa,
                    soc,
                    "leak-test-pressure-drop",
                )
            self._phase = FuelingPhase.FILLING
            self._leak_check_until_s = None
            self._leak_check_reference_pressure_pa = None
            if self.schedule.leak_check_pressure_interval_pa is not None:
                self._next_leak_check_pressure_pa = (
                    observation.pressure_pa
                    + self.schedule.leak_check_pressure_interval_pa
                )

        if (
            self._phase is FuelingPhase.FILLING
            and self._next_leak_check_pressure_pa is not None
            and observation.pressure_pa >= self._next_leak_check_pressure_pa
        ):
            self._phase = FuelingPhase.LEAK_CHECK
            self._leak_check_until_s = observation.time_s + self.schedule.leak_check_pause_s
            self._leak_check_reference_pressure_pa = observation.pressure_pa
            return self._paused_command(
                reference_pressure_pa,
                soc,
                "leak-check-pause",
                observation.time_s,
            )

        if self._phase is not FuelingPhase.FILLING:
            return self._stopped_command(reference_pressure_pa, soc, "controller-not-filling")

        error_pa = reference_pressure_pa - observation.pressure_pa
        candidate_integral = self._integral_error_pa_s + error_pa * sample_period_s
        raw_opening = (
            self.parameters.proportional_gain_pa_inverse * error_pa
            + self.parameters.integral_gain_pa_inverse_s_inverse * candidate_integral
        )
        amplitude_bounded_opening = min(
            self.parameters.maximum_opening,
            max(self.parameters.minimum_opening, raw_opening),
        )

        bounded_opening = amplitude_bounded_opening
        if observation.measured_mass_flow_kg_s > self.schedule.maximum_mass_flow_kg_s:
            bounded_opening *= (
                self.schedule.maximum_mass_flow_kg_s
                / observation.measured_mass_flow_kg_s
            )

        maximum_step = self.parameters.maximum_opening_slew_per_s * sample_period_s
        opening = min(
            self._last_opening + maximum_step,
            max(self._last_opening - maximum_step, bounded_opening),
        )
        self._last_opening = opening

        actuator_limited = abs(opening - raw_opening) > 1.0e-12
        integration_drives_toward_available_range = (
            (opening < raw_opening and error_pa < 0.0)
            or (opening > raw_opening and error_pa > 0.0)
        )
        if not actuator_limited or integration_drives_toward_available_range:
            self._integral_error_pa_s = candidate_integral
        # Otherwise hold the integrator. Flow limiting, static valve bounds,
        # and slew limiting are all actuator constraints. Back-calculating a
        # flow-limited opening through the integral gain can reverse the stored
        # error and latch the valve shut while pressure error is still positive.

        return FuelingCommand(
            phase=self._phase,
            valve_opening=opening,
            reference_pressure_pa=reference_pressure_pa,
            delivery_temperature_target_k=self.schedule.delivery_temperature_at(
                observation.time_s
            ),
            state_of_charge=soc,
        )

    def _stopped_command(
        self,
        reference_pressure_pa: float,
        soc: float,
        reason: str,
    ) -> FuelingCommand:
        self._last_opening = 0.0
        return FuelingCommand(
            phase=self._phase,
            valve_opening=0.0,
            reference_pressure_pa=reference_pressure_pa,
            delivery_temperature_target_k=self.schedule.delivery_temperature_at(
                self._start_time_s
            ),
            state_of_charge=soc,
            stop_reason=reason,
        )

    def _paused_command(
        self,
        reference_pressure_pa: float,
        soc: float,
        reason: str,
        time_s: float,
    ) -> FuelingCommand:
        self._last_opening = 0.0
        return FuelingCommand(
            phase=self._phase,
            valve_opening=0.0,
            reference_pressure_pa=reference_pressure_pa,
            delivery_temperature_target_k=self.schedule.delivery_temperature_at(time_s),
            state_of_charge=soc,
            stop_reason=reason,
        )
