"""Fueling-protocol control primitives.

This module intentionally does not reproduce proprietary SAE J2601 lookup tables.
It accepts a schedule generated by an authorized table implementation, MC Formula,
or a supervisory station controller and applies it to the dynamic tank model.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from .tabulated import PropsSI


class FuelingPhase(str, Enum):
    IDLE = "idle"
    FILLING = "filling"
    COMPLETE = "complete"
    ABORTED = "aborted"


@dataclass(frozen=True)
class FuelingSchedule:
    """Externally supplied SAE J2601-compatible fueling setpoints, in SI units."""

    target_pressure_pa: float
    average_pressure_ramp_rate_pa_s: float
    delivery_temperature_k: float
    maximum_mass_flow_kg_s: float
    maximum_gas_temperature_k: float = 358.15
    target_soc: float = 1.0
    nominal_working_pressure_pa: float = 70.0e6
    reference_temperature_k: float = 288.15

    def __post_init__(self) -> None:
        if self.target_pressure_pa <= 0.0:
            raise ValueError("target_pressure_pa must be positive")
        if self.average_pressure_ramp_rate_pa_s <= 0.0:
            raise ValueError("average_pressure_ramp_rate_pa_s must be positive")
        if self.maximum_mass_flow_kg_s <= 0.0:
            raise ValueError("maximum_mass_flow_kg_s must be positive")
        if not 0.0 < self.target_soc <= 1.2:
            raise ValueError("target_soc must be in (0, 1.2]")


@dataclass(frozen=True)
class FuelingControllerParameters:
    proportional_gain_pa_inverse: float = 3.0e-8
    integral_gain_pa_inverse_s_inverse: float = 2.0e-10
    minimum_opening: float = 0.0
    maximum_opening: float = 1.0
    completion_pressure_tolerance_pa: float = 1.0e5
    anti_windup_gain: float = 0.5
    maximum_opening_slew_per_s: float = 0.03


@dataclass(frozen=True)
class FuelingObservation:
    time_s: float
    pressure_pa: float
    temperature_k: float
    density_kg_m3: float
    measured_mass_flow_kg_s: float


@dataclass(frozen=True)
class FuelingCommand:
    phase: FuelingPhase
    valve_opening: float
    reference_pressure_pa: float
    delivery_temperature_target_k: float
    state_of_charge: float
    stop_reason: str | None = None


class VehicleStateOfCharge:
    """Density-based compressed-hydrogen vehicle SOC definition."""

    def __init__(self, schedule: FuelingSchedule, fluid: str = "Hydrogen") -> None:
        self.reference_density_kg_m3 = float(
            PropsSI(
                "Dmass",
                "P",
                schedule.nominal_working_pressure_pa,
                "T",
                schedule.reference_temperature_k,
                fluid,
            )
        )

    def calculate(self, density_kg_m3: float) -> float:
        return density_kg_m3 / self.reference_density_kg_m3


class SampledFuelingController:
    """Sampled PI pressure-ramp controller with independent safety termination."""

    def __init__(
        self,
        schedule: FuelingSchedule,
        parameters: FuelingControllerParameters | None = None,
        fluid: str = "Hydrogen",
    ) -> None:
        self.schedule = schedule
        self.parameters = parameters or FuelingControllerParameters()
        self.soc_model = VehicleStateOfCharge(schedule, fluid)
        self._phase = FuelingPhase.IDLE
        self._start_time_s = 0.0
        self._initial_pressure_pa = 0.0
        self._integral_error_pa_s = 0.0
        self._last_opening = 0.0

    def start(self, time_s: float, initial_pressure_pa: float) -> None:
        self._phase = FuelingPhase.FILLING
        self._start_time_s = time_s
        self._initial_pressure_pa = initial_pressure_pa
        self._integral_error_pa_s = 0.0
        self._last_opening = 0.0

    def reset(self) -> None:
        """Return the controller to idle before a separate operator fill request."""
        self._phase = FuelingPhase.IDLE
        self._integral_error_pa_s = 0.0
        self._last_opening = 0.0

    def update(self, observation: FuelingObservation, sample_period_s: float,
               *, auto_stop: bool = True, target_pressure_pa: float | None = None) -> FuelingCommand:
        if self._phase is FuelingPhase.IDLE:
            self.start(observation.time_s, observation.pressure_pa)

        elapsed_s = max(0.0, observation.time_s - self._start_time_s)
        target = target_pressure_pa or self.schedule.target_pressure_pa
        ramp_reference = self._initial_pressure_pa + self.schedule.average_pressure_ramp_rate_pa_s * elapsed_s
        reference_pressure_pa = min(target, ramp_reference) if auto_stop else min(110e6, ramp_reference)
        soc = self.soc_model.calculate(observation.density_kg_m3)

        if observation.temperature_k >= self.schedule.maximum_gas_temperature_k:
            self._phase = FuelingPhase.ABORTED
            return self._stopped_command(reference_pressure_pa, soc, "gas-temperature-limit")

        pressure_complete = observation.pressure_pa >= (
            target
            - self.parameters.completion_pressure_tolerance_pa
        )
        if auto_stop and (pressure_complete or soc >= self.schedule.target_soc):
            self._phase = FuelingPhase.COMPLETE
            reason = "target-pressure" if pressure_complete else "target-soc"
            return self._stopped_command(reference_pressure_pa, soc, reason)

        if self._phase is not FuelingPhase.FILLING:
            return self._stopped_command(reference_pressure_pa, soc, "controller-not-filling")

        error_pa = reference_pressure_pa - observation.pressure_pa
        candidate_integral = self._integral_error_pa_s + error_pa * sample_period_s
        raw_opening = (
            self.parameters.proportional_gain_pa_inverse * error_pa
            + self.parameters.integral_gain_pa_inverse_s_inverse * candidate_integral
        )
        bounded_opening = min(
            self.parameters.maximum_opening,
            max(self.parameters.minimum_opening, raw_opening),
        )

        if observation.measured_mass_flow_kg_s > self.schedule.maximum_mass_flow_kg_s:
            bounded_opening *= (
                self.schedule.maximum_mass_flow_kg_s
                / observation.measured_mass_flow_kg_s
            )

        maximum_step = self.parameters.maximum_opening_slew_per_s * sample_period_s
        opening = min(
            self._last_opening + maximum_step,
            max(self._last_opening - maximum_step, bounded_opening),
        )
        self._last_opening = opening

        amplitude_saturated = abs(bounded_opening - raw_opening) > 1.0e-12
        slew_limited = abs(opening - bounded_opening) > 1.0e-12
        if not amplitude_saturated and not slew_limited:
            self._integral_error_pa_s = candidate_integral
        elif amplitude_saturated:
            # Back-calculate only against the static actuator bound. Applying
            # the same correction to a temporary slew-rate limit can move the
            # integrator by orders of magnitude and reverse an otherwise
            # positive pressure error on the following sample.
            self._integral_error_pa_s += (
                self.parameters.anti_windup_gain
                * (bounded_opening - raw_opening)
                * sample_period_s
                / max(self.parameters.integral_gain_pa_inverse_s_inverse, 1.0e-30)
            )

        return FuelingCommand(
            phase=self._phase,
            valve_opening=opening,
            reference_pressure_pa=reference_pressure_pa,
            delivery_temperature_target_k=self.schedule.delivery_temperature_k,
            state_of_charge=soc,
        )

    def _stopped_command(
        self,
        reference_pressure_pa: float,
        soc: float,
        reason: str,
    ) -> FuelingCommand:
        self._last_opening = 0.0
        return FuelingCommand(
            phase=self._phase,
            valve_opening=0.0,
            reference_pressure_pa=reference_pressure_pa,
            delivery_temperature_target_k=self.schedule.delivery_temperature_k,
            state_of_charge=soc,
            stop_reason=reason,
        )
