"""Verify the Cirrone 2022 delayed-ignition implementation against paper values."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from h2station.risk.delayed_ignition import (  # noqa: E402
    CIRRONE_DOI,
    delayed_ignition_overpressure_pa,
    delayed_ignition_radial_distance_m,
)


PAPER_PDF_SHA256 = "ab8bf68cb33fa1fa2d2134429f14146e8c24fc0c618a0e15a4f16f8a2a67e4a8"
IMPLEMENTATION = ROOT / "src/h2station/risk/delayed_ignition.py"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_report() -> dict[str, object]:
    forward_actual_kpa = delayed_ignition_overpressure_pa(
        70e6, 0.002, 2.03
    ) / 1000.0
    forward_expected_kpa = 21.9
    forward_error_kpa = abs(forward_actual_kpa - forward_expected_kpa)

    thresholds = {
        "no_harm": 1_350.0,
        "injury": 16_500.0,
        "fatality": 100_000.0,
    }
    # Table 4 radial distances from the centre of the fast-burning mixture.
    applications = (
        ("vehicle_0_5_mm", 70.0, 0.5, (2.2, 0.6, 0.2)),
        ("vehicle_1_mm", 70.0, 1.0, (4.4, 1.2, 0.5)),
        ("vehicle_2_mm", 70.0, 2.0, (8.8, 2.4, 0.9)),
        ("train_5_mm", 70.0, 5.0, (22.0, 5.9, 2.3)),
        ("bus_5_mm", 35.0, 5.0, (18.5, 5.0, 1.9)),
        ("pipeline_114_mm", 5.8, 114.0, (269.3, 72.1, 27.9)),
        ("pipeline_220_mm", 5.8, 220.0, (519.7, 139.2, 53.9)),
        ("hrs_storage_5_mm", 95.0, 5.0, (23.8, 6.4, 2.5)),
    )
    rows: list[dict[str, object]] = []
    names = tuple(thresholds)
    for application, pressure_mpa, diameter_mm, expected_values in applications:
        for index, name in enumerate(names):
            actual = delayed_ignition_radial_distance_m(
                pressure_mpa * 1e6,
                diameter_mm / 1000.0,
                thresholds[name],
            )
            expected = expected_values[index]
            error = abs(actual - expected)
            tolerance = max(0.06, expected * 0.003)
            rows.append({
                "application": application,
                "storage_pressure_mpa": pressure_mpa,
                "release_diameter_mm": diameter_mm,
                "threshold": name,
                "threshold_pa": thresholds[name],
                "paper_radial_distance_m": expected,
                "implementation_radial_distance_m": actual,
                "absolute_error_m": error,
                "tolerance_m": tolerance,
                "passed": error <= tolerance,
            })

    all_passed = forward_error_kpa <= 0.1 and all(bool(row["passed"]) for row in rows)
    return {
        "schema_version": 1,
        "artifact_type": "cirrone_2022_delayed_ignition_implementation_benchmark",
        "status": "passed" if all_passed else "failed",
        "generated_date_utc": "2026-10-08",
        "source": {
            "citation": (
                "Cirrone et al., Blast Wave Generated by Delayed Ignition of "
                "Under-Expanded Hydrogen Free Jet at Ambient and Cryogenic "
                "Temperatures, Hydrogen 3 (2022) 433-449"
            ),
            "doi": CIRRONE_DOI,
            "url": "https://doi.org/10.3390/hydrogen3040027",
            "open_access_license": "CC BY 4.0",
            "paper_pdf_sha256": PAPER_PDF_SHA256,
            "experimental_case_count_reported": 78,
        },
        "implementation": {
            "path": str(IMPLEMENTATION.relative_to(ROOT)).replace("\\", "/"),
            "sha256": _sha256(IMPLEMENTATION),
            "equation": (
                "delta_p/p0 = 5000 * [ (ps/p0)^0.5 * (d/rw)^2 ]^0.95"
            ),
            "distance_origin": "centre of 25-35 vol% hydrogen cloud",
        },
        "forward_benchmark": {
            "paper_section": "5.1, Equation (7)",
            "storage_pressure_mpa": 70.0,
            "release_diameter_mm": 2.0,
            "wave_distance_m": 2.03,
            "paper_overpressure_kpa": forward_expected_kpa,
            "implementation_overpressure_kpa": forward_actual_kpa,
            "absolute_error_kpa": forward_error_kpa,
            "tolerance_kpa": 0.1,
            "passed": forward_error_kpa <= 0.1,
        },
        "inverse_benchmarks": rows,
        "aggregate": {
            "inverse_case_count": len(rows),
            "inverse_pass_count": sum(bool(row["passed"]) for row in rows),
            "maximum_absolute_error_m": max(float(row["absolute_error_m"]) for row in rows),
            "forward_passed": forward_error_kpa <= 0.1,
            "all_passed": all_passed,
        },
        "validation_domain": {
            "storage_pressure_mpa": [0.5, 65.0],
            "storage_temperature_k": [80.0, 300.0],
            "release_diameter_mm": [0.5, 52.5],
            "geometry": "under-expanded free jet; horizontal or vertically upward",
            "obstacle_or_confinement_effects": False,
        },
        "runtime_contract": {
            "hybrid_replacement_of_hyram": False,
            "free_orifice_only": True,
            "flow_limited_source_fails_closed": True,
            "reported_as_cloud_centred_radial_comparison": True,
            "site_safety_distance": False,
        },
        "claim_boundary": (
            "This verifies the software transcription against Equation (5), Equation "
            "(7), and rounded Table 4 values from the same publication. The paper's "
            "78 experiments support the published correlation, but these checks are "
            "not independent validation by this project. Distances are radial from the "
            "fast-burning cloud centre and are not leak-centred site safety, evacuation, "
            "probability, obstacle, impingement, confinement, or full-station results."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "research/cirrone_2022_delayed_ignition_benchmark.json",
    )
    args = parser.parse_args()
    report = build_report()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    if report["status"] != "passed":
        raise SystemExit("Cirrone delayed-ignition implementation benchmark failed")


if __name__ == "__main__":
    main()
